import Foundation

/// GPU monitor.
/// iOS does not expose system-wide GPU utilization to third-party apps.
/// DeviceLab can legitimately report:
/// - its own GPU time accumulated via MetricKit (MXGPUMetric)
/// - GPU workload generated by DeviceLab's own Metal benchmarks
/// Arbitrary installed-app GPU usage is NOT available and is never fabricated.
@MainActor
final class GPUMonitor: BaseMonitor {
    private(set) var metricKitGPUTime: TimeInterval?
    private(set) var lastBenchmarkFPS: Double?
    private(set) var lastBenchmarkFrameTime: Double?
    private(set) var lastBenchmarkAt: Date?

    init() {
        super.init(kind: .gpu)
        setAvailability(.unavailable("System GPU attribution is not available through public third-party iOS APIs."))
    }

    override func refresh() async {
        let detail = """
        GPU system app attribution:
        Not available through public third-party iOS APIs.

        DeviceLab GPU time (MetricKit MXGPUMetric):
        \(metricKitGPUTime.map { String(format: "%.2f s cumulative", $0) } ?? "No MetricKit payload received yet")

        DeviceLab GPU benchmark:
        \(lastBenchmarkFPS.map { String(format: "%.0f FPS", $0) } ?? "Not run yet")
        \(lastBenchmarkFrameTime.map { String(format: "%.1f ms frame time", $0) } ?? "")
        """

        var valueText = "Measured"
        if let lastBenchmarkFPS {
            valueText = String(format: "%.0f FPS", lastBenchmarkFPS)
        }
        var subtext = "DeviceLab own workload"
        if let lastBenchmarkAt {
            subtext = "Last benchmark \(Formatters.timeShort(lastBenchmarkAt))"
        }

        updateSnapshot(MetricSnapshot(
            kind: .gpu,
            valueText: valueText,
            subtext: subtext,
            detail: detail,
            status: .unavailable("System attribution restricted; DeviceLab own GPU is measured"),
            provenance: .measuredByDeviceLab,
            updatedAt: lastBenchmarkAt ?? Date(),
            numericValue: lastBenchmarkFPS,
            unit: "FPS"
        ))
    }

    /// Called by the GPU benchmark coordinator when a benchmark completes.
    func recordBenchmarkResult(fps: Double, frameTime: Double) {
        lastBenchmarkFPS = fps
        lastBenchmarkFrameTime = frameTime
        lastBenchmarkAt = Date()
        Task { await refresh() }
    }

    /// Called by the MetricKit manager when a payload containing GPU time arrives.
    func recordMetricKitGPUTime(_ seconds: TimeInterval) {
        metricKitGPUTime = seconds
        Task { await refresh() }
    }
}